# Generated by Django 4.1.2 on 2022-11-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harishapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradd',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='useradd',
            name='lname',
        ),
    ]
