# Generated by Django 4.1.2 on 2022-11-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harishapp', '0002_remove_useradd_fname_remove_useradd_lname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradd',
            name='pass2',
        ),
    ]
