# Generated by Django 4.1.3 on 2022-11-21 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harishapp', '0003_remove_useradd_pass2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='useradd',
        ),
    ]
